// Continent-to-country mapping for accurate geographic classification
export const CONTINENT_MAPPING: Record<string, string[]> = {
  Asia: [
    "China",
    "India",
    "Indonesia",
    "Pakistan",
    "Bangladesh",
    "Japan",
    "Philippines",
    "Vietnam",
    "Turkey",
    "Iran",
    "Thailand",
    "Myanmar",
    "South Korea",
    "Iraq",
    "Afghanistan",
    "Saudi Arabia",
    "Uzbekistan",
    "Malaysia",
    "Nepal",
    "Yemen",
    "North Korea",
    "Sri Lanka",
    "Kazakhstan",
    "Syria",
    "Cambodia",
    "Jordan",
    "Azerbaijan",
    "United Arab Emirates",
    "Tajikistan",
    "Israel",
    "Laos",
    "Singapore",
    "Oman",
    "Kuwait",
    "Georgia",
    "Mongolia",
    "Armenia",
    "Qatar",
    "Bahrain",
    "East Timor",
    "Palestine",
    "Lebanon",
    "Kyrgyzstan",
    "Turkmenistan",
    "Bhutan",
    "Brunei",
    "Maldives",
    "Russia",
  ],
  Africa: [
    "Nigeria",
    "Ethiopia",
    "Egypt",
    "South Africa",
    "Kenya",
    "Uganda",
    "Algeria",
    "Sudan",
    "Morocco",
    "Angola",
    "Ghana",
    "Mozambique",
    "Madagascar",
    "Cameroon",
    "Ivory Coast",
    "Niger",
    "Burkina Faso",
    "Mali",
    "Malawi",
    "Zambia",
    "Senegal",
    "Somalia",
    "Chad",
    "Zimbabwe",
    "Guinea",
    "Rwanda",
    "Benin",
    "Burundi",
    "Tunisia",
    "Togo",
    "Sierra Leone",
    "Libya",
    "Liberia",
    "Central African Republic",
    "Mauritania",
    "Eritrea",
    "Gambia",
    "Botswana",
    "Namibia",
    "Gabon",
    "Lesotho",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Mauritius",
    "Eswatini",
    "Djibouti",
    "Comoros",
    "Cape Verde",
    "São Tomé and Príncipe",
    "Seychelles",
    "South Sudan",
    "Tanzania",
    // Exact GeoJSON names for missing countries
    "Dem. Rep. Congo",
    "Congo",
    "Central African Rep.",
    "W. Sahara",
    "Côte d'Ivoire",
  ],
  Europe: [
    "Germany",
    "United Kingdom",
    "France",
    "Italy",
    "Spain",
    "Ukraine",
    "Poland",
    "Romania",
    "Netherlands",
    "Belgium",
    "Czech Republic",
    "Greece",
    "Portugal",
    "Sweden",
    "Hungary",
    "Austria",
    "Belarus",
    "Switzerland",
    "Bulgaria",
    "Serbia",
    "Denmark",
    "Finland",
    "Slovakia",
    "Norway",
    "Ireland",
    "Croatia",
    "Bosnia and Herzegovina",
    "Albania",
    "Lithuania",
    "Slovenia",
    "Latvia",
    "Estonia",
    "Macedonia",
    "Moldova",
    "Luxembourg",
    "Malta",
    "Iceland",
    "Montenegro",
    "Cyprus",
    "Andorra",
    "Liechtenstein",
    "Monaco",
    "San Marino",
    "Vatican City",
    "Kosovo",
  ],
  "North America": [
    "United States",
    "Canada",
    "Mexico",
    "Guatemala",
    "Cuba",
    "Haiti",
    "Dominican Republic",
    "Honduras",
    "Nicaragua",
    "Costa Rica",
    "Panama",
    "Jamaica",
    "Trinidad and Tobago",
    "Bahamas",
    "Belize",
    "Barbados",
    "Saint Lucia",
    "Grenada",
    "Saint Vincent and the Grenadines",
    "Antigua and Barbuda",
    "Dominica",
    "Saint Kitts and Nevis",
    "El Salvador",
  ],
  "South America": [
    "Brazil",
    "Argentina",
    "Peru",
    "Colombia",
    "Chile",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Guyana",
    "Suriname",
    "French Guiana",
  ],
  Oceania: [
    "Australia",
    "Papua New Guinea",
    "New Zealand",
    "Fiji",
    "Solomon Islands",
    "Vanuatu",
    "Samoa",
    "Micronesia",
    "Tonga",
    "Kiribati",
    "Palau",
    "Marshall Islands",
    "Tuvalu",
    "Nauru",
  ],
};

// Optimal zoom coordinates for each continent (manually determined)
export const CONTINENT_ZOOM_COORDS = {
  Africa: { zoom: 3.5, x: -1487, y: -668 },
  "South America": { zoom: 3.5, x: -1033, y: -938 },
  "North America": { zoom: 3.5, x: -754, y: -332 },
  Oceania: { zoom: 4, x: -2948, y: -1223 },
  Europe: { zoom: 5.5, x: -2853, y: -598 },
  Asia: { zoom: 3, x: -1739, y: -250 },
};

// SVG Map configuration constants
export const SVG_MAP_CONFIG = {
  width: 1200,
  height: 600,
  initialZoom: 1.5,
  initialX: -340,
  initialY: -94,
  zoomExtent: [1.5, 8] as [number, number], // Minimum zoom is now 1.5, maximum is 8
  dataUrl: "/world-countries.geojson",
};
