// Continent-to-country mapping for accurate geographic classification
// Updated to match exact GeoJSON country names and ensure flag compatibility
export const CONTINENT_MAPPING: Record<string, string[]> = {
  Asia: [
    "China",
    "India",
    "Indonesia",
    "Pakistan",
    "Bangladesh",
    "Japan",
    "Philippines",
    "Vietnam",
    "Iran",
    "Thailand",
    "Myanmar",
    "South Korea",
    "Iraq",
    "Afghanistan",
    "Saudi Arabia",
    "Uzbekistan",
    "Malaysia",
    "Nepal",
    "Yemen",
    "North Korea",
    "Sri Lanka",
    "Kazakhstan",
    "Syria",
    "Cambodia",
    "Jordan",
    "United Arab Emirates",
    "Tajikistan",
    "Israel",
    "Laos",
    "Singapore",
    "Oman",
    "Kuwait",
    "Mongolia",
    "Qatar",
    "Bahrain",
    "Timor-Leste", // Fixed: was "East Timor"
    "Palestine",
    "Lebanon",
    "Kyrgyzstan",
    "Turkmenistan",
    "Bhutan",
    "Brunei",
    // Transcontinental countries - Asian part
    "Russia", // Mostly in Asia
    "Turkey", // Mostly in Asia (Anatolia)
    "Georgia", // Transcontinental, traditionally considered Asia
    "Armenia", // Transcontinental, traditionally considered Asia
    "Azerbaijan", // Transcontinental, traditionally considered Asia
    // Additional Asian countries from GeoJSON
    "Taiwan",
    "Macao",
  ],
  Africa: [
    "Nigeria",
    "Ethiopia",
    "Egypt",
    "South Africa",
    "Kenya",
    "Uganda",
    "Algeria",
    "Sudan",
    "Morocco",
    "Angola",
    "Ghana",
    "Mozambique",
    "Madagascar",
    "Cameroon",
    "Niger",
    "Burkina Faso",
    "Mali",
    "Malawi",
    "Zambia",
    "Senegal",
    "Somalia",
    "Chad",
    "Zimbabwe",
    "Guinea",
    "Rwanda",
    "Benin",
    "Burundi",
    "Tunisia",
    "Togo",
    "Sierra Leone",
    "Libya",
    "Liberia",
    "Mauritania",
    "Eritrea",
    "Gambia",
    "Botswana",
    "Namibia",
    "Gabon",
    "Lesotho",
    "Guinea-Bissau",
    "Mauritius",
    "eSwatini", // Fixed: was "Eswatini"
    "Djibouti",
    "Cabo Verde", // Fixed: was "Cape Verde"
    "Tanzania",
    // Exact GeoJSON names
    "Dem. Rep. Congo",
    "Congo",
    "Central African Rep.", // Fixed: was "Central African Republic"
    "W. Sahara",
    "Côte d'Ivoire", // Fixed: removed duplicate "Ivory Coast"
    "S. Sudan", // Fixed: was "South Sudan"
    "São Tomé and Principe", // Fixed: was "São Tomé and Príncipe"
    "Eq. Guinea", // Fixed: was "Equatorial Guinea"
  ],
  Europe: [
    "Germany",
    "United Kingdom",
    "France",
    "Italy",
    "Spain",
    "Ukraine",
    "Poland",
    "Romania",
    "Netherlands",
    "Belgium",
    "Czechia", // Fixed: was "Czech Republic"
    "Greece",
    "Portugal",
    "Sweden",
    "Hungary",
    "Austria",
    "Belarus",
    "Switzerland",
    "Bulgaria",
    "Serbia",
    "Denmark",
    "Finland",
    "Slovakia",
    "Norway",
    "Ireland",
    "Croatia",
    "Bosnia and Herz.", // Fixed: was "Bosnia and Herzegovina"
    "Albania",
    "Lithuania",
    "Slovenia",
    "Latvia",
    "Estonia",
    "North Macedonia", // Fixed: was "Macedonia"
    "Moldova",
    "Luxembourg",
    "Malta",
    "Iceland",
    "Montenegro",
    "Cyprus",
    "Andorra",
    "Liechtenstein",
    "Monaco",
    "San Marino",
    "Vatican", // Fixed: was "Vatican City"
    "Kosovo",
    // Additional European territories from GeoJSON
    "Guernsey",
    "Jersey",
    "Isle of Man",
    "N. Cyprus",
    "Åland",
  ],
  "North America": [
    "United States of America", // Fixed: was "United States"
    "Canada",
    "Mexico",
    "Guatemala",
    "Cuba",
    "Haiti",
    "Dominican Rep.", // Fixed: was "Dominican Republic"
    "Honduras",
    "Nicaragua",
    "Costa Rica",
    "Panama",
    "Jamaica",
    "Trinidad and Tobago",
    "Bahamas",
    "Belize",
    "Barbados",
    "Saint Lucia",
    "Grenada",
    "Saint Vincent and the Grenadines",
    "Antigua and Barb.", // Fixed: was "Antigua and Barbuda"
    "Dominica",
    "Saint Kitts and Nevis",
    "El Salvador",
    // Additional North American territories from GeoJSON
    "Curaçao",
  ],
  "South America": [
    "Brazil",
    "Argentina",
    "Peru",
    "Colombia",
    "Chile",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Guyana",
    "Suriname",
    "French Guiana", // Now split from France MultiPolygon in processing
  ],
  Oceania: [
    "Australia",
    "Papua New Guinea",
    "New Zealand",
    "Fiji",
    "Solomon Islands",
    "Vanuatu",
    "Samoa",
    "Micronesia",
    "Tonga",
    "Kiribati",
    "Palau",
    "Marshall Islands",
    "Tuvalu",
    "Nauru",
  ],
};

// Optimal zoom coordinates for each continent (manually determined)
export const CONTINENT_ZOOM_COORDS = {
  Africa: { zoom: 3.5, x: -1487, y: -668 },
  "South America": { zoom: 3.5, x: -1033, y: -938 },
  "North America": { zoom: 3.5, x: -754, y: -332 },
  Oceania: { zoom: 4, x: -2948, y: -1223 },
  Europe: { zoom: 5.5, x: -2853, y: -598 },
  Asia: { zoom: 3, x: -1739, y: -250 },
};

// SVG Map configuration constants
export const SVG_MAP_CONFIG = {
  width: 1200,
  height: 600,
  initialZoom: 1.0, // Reduced initial zoom for Equirectangular projection
  initialX: 0, // Centered for Equirectangular
  initialY: 0, // Centered for Equirectangular
  zoomExtent: [1.0, 8] as [number, number], // Adjusted minimum zoom
  dataUrl: "/world-countries.geojson",
};
